apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-devops-platform.fullname" . }}-secret
  labels:
    {{- include "ai-devops-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.appSecret.apiKey | quote }}